# dataset
dataset_type: 'SDD'
obs_len: 8
pred_len: 12
num_epoch: 60
batch_size: 32
num_sample: 20
data_scale: 50
# optimizer
lr: 1e-3
weight_decay: 1e-4
decay_step: 10
decay_gamma: 0.5
# hyper parameter for training
hyper_param1: 5
hyper_param2: 1
# model parameters
num_layers: 2
num_heads: 4
latent_dim: 256
context_dim: 256
mamba_dim: 128
# diffusion
timesteps: 1000
scheduler: 'cosine' # 'cosine' 'linear' 'quad' 'sigmoid'
num_tau: 3
scale_param: 1e-5
ema: True
